services:
  db:
    image: postgres:16-alpine
    container_name: local-drop-postgres
    restart: always
    environment:
      POSTGRES_USER: localdrop_user
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: localdrop_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: local-drop-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend/uploads:/app/backend/uploads
    environment:
      DATABASE_URL: postgresql://localdrop_user:supersecretpassword@db:5432/localdrop_db?schema=public
      APP_PIN: "693413"
      ADMIN_PASSWORD: Y4EbalR0t_Tvo3iShluhi@Mamfsh1xDloX
      JWT_SECRET: :>SufSyX6u|<XD*L1QB_ZJ*LIM8QG=K&.kZhj^t56Z+v*ctUmdtnp(n}q+C+&IGp^ksLX>$34T0r)ktUKH^S=V

  frontend:
    container_name: local-drop-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: